version: "3"

services:
  postgres_kruger:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: vaccine
    ports:
      - "5431:5432"